# Generated by Django 4.0.3 on 2022-04-06 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_batch_branch_staff_batch_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='branch_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_branch_from', to='api.branch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='branch_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_branch_to', to='api.branch'),
        ),
    ]
