# Generated by Django 4.0.3 on 2022-04-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_username_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_branch', to='api.branch'),
        ),
    ]
