# Generated by Django 4.0.3 on 2022-04-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_password'),
        ('api', '0003_batch_created_by'),
    ]

    operations = [
    ]
