# Generated by Django 4.0.3 on 2022-04-07 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_batch_branch_from_alter_batch_branch_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('dispatched', 'DISPATCHED'), ('delivered', 'DELIVERED')], default='dispatched', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_order', to='api.batch'),
        ),
    ]
