# Generated by Django 4.0.3 on 2022-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_batch_branch_from_alter_batch_branch_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('dispatched', 'DISPATCHED'), ('delivered', 'DELIVERED')], default='dispatched', max_length=30),
        ),
    ]
