# Generated by Django 4.0.3 on 2022-04-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_batch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='departure_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_orders', to='api.batch'),
        ),
    ]
