# Generated by Django 4.0.3 on 2022-04-07 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_batch_departure_time_alter_order_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
