# Generated by Django 4.0.3 on 2022-04-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_batch_departure_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-departure_time']},
        ),
        migrations.AddField(
            model_name='batch',
            name='manager_delivey_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='manager_status',
            field=models.CharField(choices=[('dispatched', 'DISPATCHED'), ('delivered', 'DELIVERED')], default='dispatched', max_length=30),
        ),
        migrations.AddField(
            model_name='batch',
            name='rider_delivery_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='rider_status',
            field=models.CharField(choices=[('dispatched', 'DISPATCHED'), ('delivered', 'DELIVERED')], default='dispatched', max_length=30),
        ),
        migrations.AlterField(
            model_name='batch',
            name='delivery_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
